# Site settings
name: Sticky Pixel
email: info@stickypixel.com
url: http://www.stickypixel.com
baseurl: /
author: Chris Sargent
keywords: webapp, progressive webapp, digital product, digital design, app development, development, product design, product development, france, 06, riviera, antibes, nice, juan-les-pins, monaco, cannes, alpes-maritimes, english-speaking
twitter_username: Chris5argent
github_username: stickypixel
linkedin_page: sticky-pixel
facebook_page: stickypixel
instagram_user: chris5argent
pinterest_user: stickypixel
youtube_user: stickypixelrocks
pinterest_verify: 185745922478d5e2f01bedcb16a93d11
bing_verify: B15758C08831D1D7033389623B947D8A
fb_app_id: 292220120802626
fb_admins: 731575475
fb_profile_id: 1599401430312734
og_image: sticky-pixel-og-image.jpg
og_logo: sticky-pixel-logo-square.jpg
telephone: +33 652 15 13 00
foundingDate: 2015-05-01
founder: Chris Sargent
address: 29 Crick Road, Rugby, Warwickshire, CV21 4DU
fraddress: Le Saphir, Rue Bricka, Juan&#8209;les&#8209;Pins, 06160&nbsp;France
legal_name: Sticky Pixel Ltd
company_no: 828790030 RCS Antibes
assets: '/assets'
images: '/assets/img'

# Build settings
markdown: kramdown
source: src
destination: dist
exclude: [assets]
keep_files: [assets]
incremental: false
collections:
  home:
    output: false
  team:
    output: false
  work:
    output: true

primary_nav:
  - url: '/'
    text: Home
  - url: '#about'
    text: About Us
  - url: '#work'
    text: Work
  - url: '#services'
    text: Services
  - url: '#team'
    text: Team
  - url: '#contact'
    text: Contact Us

plugins:
  - jekyll-sitemap
  - jekyll-contentblocks
